public class NewClass{

  public NewClass(){}

  public bedMethod(Integer param){
    param=5;
    //I need to find another quick example lol
    //Trigger
  }
public bedMethod1(Integer param){  //Bad method1
    param=5;
    //I need to find another quick example lol
    //Trigger
  } //Found Error1

public bedMethod2(Integer param){  //Bad method2
    param=5;
    //I need to find another quick example lol
    //Trigger
  }
}
