# This is a main workflow to trigger codescan

name: CodeScan

# Controls when the workflow will rundd
on:
    push:
      branches:
        - sarif-test
    pull_request:
      branches:
        - sarif-test
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Cache files
          uses: actions/cache@v2
          with:
              path: |
                  ~/.sonar
              key: ${{ runner.os }}-sonar
              restore-keys: ${{ runner.os }}-sonar
        - name: Run Codescan On Push
          if: github.event_name == 'push'
          uses: codescan-io/codescan-scanner-action@1.4
          with:
            codeScanUrl: https//:grc.codescan.io
            organization: sariftest
            projectKey: projectKeysss 
            login: ${{ secrets.codescan_token2 }}
            failOnRedQualityGate: true
        - name: Run Codescan On PR
          if: github.event_name == 'pull_request'
          uses: codescan-io/codescan-scanner-action@1.4
          with:
            codeScanUrl: https//:grc.codescan.io
            organization: sariftest
            projectKey: projectKeysss
            login: ${{ secrets.codescan_token2 }}
            generateSarifFile: true
            failOnRedQualityGate: true
            args: |
              sonar.pullrequest.branch=${{github.head_ref}}
              sonar.pullrequest.base=${{github.base_ref}}
              sonar.pullrequest.key=${{github.event.number}}
        - name: Upload SARIF file
          uses: github/codeql-action/upload-sarif@v2
          with:
            sarif_file: codescan.sarif


